spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: maple
    password: maple
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jackson:
#    serialization:
      #      WRITE_ENUMS_USING_TO_STRING: true
      #      WRITE_ENUMS_USING_INDEX: true
#      WRITE_ENUM_KEYS_USING_INDEX: true
#mybatis-plus:
#  type-enums-package: com.maple.enumeration.enums
#mybatis:
#  configuration:
#    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
